#define IND_STS 0
#define IND_LDS 1
#define IND_POP 2
#define IND_PUSH 3
#define IND_CALL 4
#define IND_LD_X 5
#define IND_LD_XpostInc 6
#define IND_LD_XpreDec 7
#define IND_LD_YpostInc 8
#define IND_LD_YpreDec 9
#define IND_LD_ZpostInc 10
#define IND_LD_ZpreDec 11
#define IND_JMP 12
#define IND_RET 13
#define IND_ADIW 14
#define IND_OUT 15
#define IND_IN 16
#define IND_ROR 17
#define IND_DEC 18
#define IND_MUL 19
#define IND_LPM_0 20
#define IND_LPM_d 21
#define IND_LPM_dpostInc 22
#define IND_SBIW 23
#define IND_LSR 24
#define IND_ST_X 25
#define IND_ST_XpostInc 26
#define IND_ST_XpreDec 27
#define IND_ST_YpostInc 28
#define IND_ST_YpreDec 29
#define IND_ST_ZpostInc 30
#define IND_ST_ZpreDec 31
#define IND_SBI 32
#define IND_CBI 33
#define IND_COM 34
#define IND_CLI 35
#define IND_INC 36
#define IND_NEG 37
#define IND_ASR 38
#define IND_ICALL 39
#define IND_SBIS 40
#define IND_RETI 41
#define IND_WDR 42
#define IND_SLEEP 43
#define IND_SBIC 44
#define IND_CLT 45
#define IND_SWAP 46
#define IND_SEI 47
#define IND_SET 48
#define IND_SEC 49
#define IND_IJMP 50
#define IND_EIJMP 51
#define IND_EICALL 52
#define IND_BSET 53
#define IND_BCLR 54
#define IND_CLC 55
#define IND_SEN 56
#define IND_CLN 57
#define IND_SEZ 58
#define IND_CLZ 59
#define IND_SES 60
#define IND_CLS 61
#define IND_SEV 62
#define IND_CLV 63
#define IND_SEH 64
#define IND_CLH 65
#define IND_ELPM_0 66
#define IND_ELPM_d 67
#define IND_ELPM_dpostInc 68
#define IND_SPM 69
#define IND_BREAK 70
#define IND_LDI 71
#define IND_RJMP 72
#define IND_MOVW 73
#define IND_MOV 74
#define IND_ADD 75
#define IND_CPC 76
#define IND_AND 77
#define IND_EOR 78
#define IND_SBC 79
#define IND_OR 80
#define IND_NOP 81
#define IND_MULSU 82
#define IND_MULS 83
#define IND_FMUL 84
#define IND_FMULS 85
#define IND_FMULSU 86
#define IND_BRBS 87
#define IND_BRBC 88
#define IND_SBRS 89
#define IND_SBRC 90
#define IND_RCALL 91
#define IND_BST 92
#define IND_BLD 93
#define IND_ADC 94
#define IND_CPI 95
#define IND_CP 96
#define IND_CPSE 97
#define IND_SUB 98
#define IND_LDD_Y 99
#define IND_LDD_Z 100
#define IND_LD_Y 101
#define IND_LD_Z 102
#define IND_STD_Y 103
#define IND_STD_Z 104
#define IND_ST_Y 105
#define IND_ST_Z 106
#define IND_SUBI 107
#define IND_ANDI 108
#define IND_SBCI 109
#define IND_ORI 110