#define MCU_RANGE_CHECK 1
#define MCU_RANGE_CHECK_ERROR 1
#define MCU_USE_INSTCACHE 1
#define SLEEP_SKIP 1

#define MCU_USE_HEAP 1

#define MCU_USE_INST_EXEC_ALG 1

#define MCU_INCLUDE_EXTRAS 1
#define MCU_RW_RECORD 0

#define MCU_WRITE_HASH 1
#define MCU_CHECK_HASH (MCU_WRITE_HASH && 1)